POST http://localhost:3018/api/blogs HTTP/1.1
Content-Type: application/json

{
  "title": "test12",
  "author": "Fan",
  "url": "http/test.com/101",
  "likes": 12
}

###
get http://localhost:3018/api/blogs

